name: github-action
env:
  apiKey: ""
  apiSecret: ""
  continuePipeline: "false"
  showTailLog: "false"
  testID: "11132497"  
  webhookURL: "https://perforcesoftwareinc.webhook.office.com/webhookb2/55a7a621-8da8-4038-b209-c17029acb527@95b666d1-9a75-49ab-95a3-8969fbcdc08c/IncomingWebhook/8df752b059714c00b2c1317b9ea24b4c/b99b43b0-b40d-4401-a0c4-5a30c07badcd"

on: push
jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run Blazemeter test
      uses: BlazeRunner-BZR/Github-Action@v8.1
      id: run-test
      with:
        apiKey: ${{env.apiKey}}
        apiSecret: ${{env.apiSecret}}
        continuePipeline: ${{env.continuePipeline}}
        showTailLog: ${{env.showTailLog}}
        testID: ${{env.testID}}
        webhookURL: ${{env.webhookURL}}
